[[ -x "$HOME/better-commit.sh" ]] && alias gcm='$HOME/better-commit.sh'
alias gd='git diff'
alias gb='git checkout "$(git branch | fzf --height=20% --reverse --info=inline | sed "s/^[* ] //")"'
alias gs='git status'
alias gp='git push'
alias gpl='git pull --recurse-submodules -j 20'
alias gplod='git pull origin develop --no-ff'
alias gplom='git pull origin master --no-ff'
alias ga='git add'
alias disc='git restore .'

alias b='cd ..'
alias bb='cd ../..'
alias bbb='cd ../../..'
alias o='open .'

alias ys='yarn start'
alias ysd='yarn start:dev'
alias ysl='yarn start:local'

alias cls='clear'
alias c='cursor .'
alias prof='cursor ~/.zshrc'
alias sauce='source ~/.zshrc'
alias clip='pbcopy'
alias copy='pbcopy'
