[window]
opacity = 0.6  # Set desired opacity level
blur = true

# Font settings (size, style, etc.)
[font]
normal = { family = "Operator Mono SSm Lig", style = "Light" }
size = 12.0

# Cursor settings (shape, blink, etc.)
[cursor]
style = { shape = "Beam" , blinking = "On" }

